"use client";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { UserContext } from "@/libraries/context";
import { useUserData } from "@/libraries/hooks";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  const userData = useUserData();
  return (
    <html lang="en">
      <body>
        <UserContext.Provider value={userData }>
          <Navbar />
          <Toaster />
          {children}
        </UserContext.Provider>
      </body>
    </html>
  );
}
